name: context
on:
  workflow_dispatch:
    inputs:
      hoge:
        type: string
        description: sample
env:
  ENV_VALUE: defined by workflow level
jobs:
  context:
    runs-on: ubuntu-latest
    env:
      ENV_VALUE_AT_JOBS: defined by workflow level
      GITHUB_ACTOR: ${{github.actor}}
      GITHUB_ACTOR_OTHER: ${GITHUB_ACTOR}
    steps:
      - run: |
          echo "${GITHUB_ACTOR} : ${{inputs.hoge}}"
      - run: |
          echo "${ENV_VALUE} : ${ENV_VALUE_AT_JOBS}"
      - run: |
          echo "${GITHUB_ACTOR_OTHER}"