name: Dump
on:
  workflow_dispatch:
    inputs:
      enable-context:
        type: boolean
        description: enable-context
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4     # ローカルアクション呼び出し前にチェックアウト
      - uses: ./.github/actions/dump/ # ローカルアクションの呼び出し
        id: dump                      # 出力値参照のためステップIDを定義
        with:
          enable-context: ${{inputs.enable-context}}    # 入力パラメータの指定
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }} # アクションの出力値を参照
