name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        description: sample
      log-level:
        type: choice
        description: log-level
        options:
          - info
          - warn
          - error
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{inputs.greeting}} : ${{inputs.log-level}}" 
