name: Github Output
on: push
jobs:
  output:
    name: Github Output
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: |
          echo "key=value" >> ${GITHUB_OUTPUT}
      - env:
          RESULT: ${{steps.source.outputs.key}}
        run: |
          echo "$RESULT"
      - run:
          echo "key2=value" >> ${GITHUB_ENV}
      - run: |
          echo "$key2"